name: Update data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-data:
    name: Update data

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Update data
        run: |
          set -euo pipefail

          # Fix pipefail
          sudo ln -sf bash /bin/sh

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          make clean
          ./update-data
          make
          git add .
          git commit -m "Update data"
          git push
